
collector:          Zapi

# Order here matters!
schedule:
  - instance: 600
  - data: 10

objects:
#  Aggregate:        aggregate.yaml
#  Volume:           volume.yaml
#  LUN:              lun.yaml
#  SnapMirror:       snapmirror.yaml
#  SystemNode:       node.yaml
  StorageDisk:      disk.yaml
#  Qtree:            qtree.yaml
#  Shelf:            shelf.yaml
