
collector:          ZapiPerf

# Order here matters!
schedule:
  - counter: 1200s
  - instance: 600s
  - data: 60s

objects:

  # Node-level metrics
  SystemNode:             system_node.yaml
  HostAdapter:            hostadapter.yaml
  Path:                   path.yaml
  FCVI:                   fcvi.yaml
  ExtCacheObj:            ext_cache_obj.yaml
  WAFL:                   wafl.yaml
  WAFLAggr:               wafl_hya_per_aggr.yaml
  WAFLSizer:              wafl_hya_sizer.yaml
  NicCommon:              nic_common.yaml
  ObjectStoreClient:      object_store_client_op.yaml
  VolumeNode:             volume_node.yaml
  TokenManager:           token_manager.yaml
  HeadroomCPU:            resource_headroom_cpu.yaml
  HeadroomAggr:           resource_headroom_aggr.yaml
