name:                       SystemNode
query:                      system-get-info
object:                     node

counters:
  system-info:
    - memory-size
    - ^maximum-aggregate-size               => max_aggr_size
    - ^maximum-flexible-volume-count        => max_vol_num
    - ^maximum-flexible-volume-size         => max_vol_size
    - ^^system-name                         => node
    - ^system-model                         => model
    - ^system-serial-number                 => serial
    - ^vendor-id                            => vendor
    - ^product-version                      => version

plugins:
  - Status:
    - status:
      label: healthy
      ok_value: true
  - Node

export_options:
  require_instance_keys: False
  instance_labels:
    - over_temperature
    - max_aggr_size
    - max_vol_size
    - max_vol_num
    - warnings
    - healthy
    - location
    - model
    - serial
    - uptime
    - vendor
    - version
  graphite_leafs:
    - node.{node}

