
name:                         SnapMirror
query:                        snapmirror-get-status
object:                       snapmirror

counters:
  snapmirror-status:
    snapmirror-status-info:
      - last-transfer-from
      - ^last-transfer-type
      - last-transfer-size
      - last-transfer-duration
      - ^^source-location             => source_node        
      - ^^destination-location        => destination_node

      - lag-time
      - status                      => status

plugins:
  - Snapmirror

export_options:
  instance_keys:
    - relationship_id
    - destination_volume
    - destination_node
    - destination_vserver
    - source_volume
    - source_vserver
    - source_node
  instance_labels:
    - healthy
    - unhealthy_reason
    - last_transfer_type
    - relationship_status
    - relationship_type
    - schedule
    - destination_node_limit
    - source_node_limit
    - group_type
  graphite_leafs:
    - node.{destination_node}.snapmirror.dest.{destination_volume}
    - node.{source_node}.snapmirror.src.{source_volume}
    - svm.{destination_vserver}.snapmirror.dest.{destination_volume}
    - svm.{source_vserver}.snapmirror.src.{source_volume}
