
name:             Disk
query:            storage-disk-get-iter
object:           disk

counters: 
  storage-disk-info:
    - ^^disk-uid
    - ^^disk-name               => disk
    - disk-inventory-info:
      - bytes-per-sector
      - capacity-sectors        => sectors
      - ^disk-type              => type
      - ^model                  => model
      - ^serial-number          => serial_number
      - ^shelf                  => shelf
      - ^shelf-bay              => shelf_bay
    - disk-ownership-info:
      - ^is-failed              => failed
      - ^home-node-name         => node
    - disk-stats-info:
      - average-latency
      - disk-io-kbps
      - disk-iops
      - power-on-time-interval  => uptime
      - path-error-count

plugins:
  - Status:
    - status:
      label: failed
      ok_value: false
    
export_options:
  instance_keys:
    - node
    - disk
  instance_labels:
    - type
    - model
    - serial_number
    - shelf
    - shelf_bay
  graphite_leafs:
    - node.{node}.disk.{disk} # take last part
