 
name:                 Qtree
query:                qtree-list-iter
object:               qtree 

instance_key:         ['vserver', 'volume', 'qtree']

instance_query:
  qtree-info:
    - qtree
    - volume
    - vserver

counters:
  qtree-info:
    - ^export-policy
    - id
    - ^oplocks
    - ^qtree
    - ^security-style
    - ^status
    - ^volume
    - ^vserver


plugins:
  Quota:
    run_after_poll: data
    counters:
    - disk-limit
    - disk-used
    - disk-used-pct-disk-limit
    - disk-used-pct-soft-disk-limit
    - disk-used-pct-threshold
    - file-limt
    - files-used
    - files-used-pct-file-limit
    - files-used-pct-soft-file-limit
    - soft-disk-limit
    - soft-file-limit
    - threshold

plugins_replace_data: False

export_options:
  exclude_instance_name: True
  labels_to_emit:
    - export_policy
    - oplocks
    - qtree
    - security_style
    - status
    - volume
    - vserver
  graphite_leafs:
    - svm.{vserver}.qtree.{qtree}