
name:                       StorageShelf
query:                      storage-shelf-info-get-iter
object:                     shelf


counters:
  storage-shelf-info:
    - disk-count
    - ^module-type
    - ^op-status
    - ^serial-number
    - ^shelf => shelf
    - ^shelf-id => shelf_id
    - ^shelf-model
    - ^^shelf-uid
    - ^state
    - ^vendor-name


plugins:
  Shelf:
    objects:
      - boot-devices => boot_device:
        storage-shelf-boot-device-info:
          - ^^boot-device-id   => device_id
          - ^boot-device-module-id => device_module_id
          - ^boot-device-size => device_size
          - ^boot-device-type => device_type
      - coin-battery:
        storage-shelf-coin-battery-info:
          - ^^coin-battery-id
          - ^coin-battery-module-id
          - coin-battery-voltage => voltage
      - cooling-fans => fan:
        storage-shelf-cooling-fan-info:
          - ^^fan-id
          - ^fan-location => location
          - fan-rpm => rpm
      - current-sensors => sensor:
        storage-shelf-current-sensor-info:
          - ^^current-sensor-id    => sensor_id
          - ^current-sensor-location => location
          - current-sensor-reading => reading
      - dimms => dimm:
        storage-shelf-dimm-info:
          - ^^dimm-id
          - ^dimm-location => location
          - ^dimm-size => size
          - ^dimm-type => type
      - fc-ports => fc_port:
        storage-shelf-fc-port-info:
          - ^^fc-port-id
      - nsm-ports => nsm_port:
        storage-shelf-nsm-port-info:
          - ^nsm-port-bay
          - ^^nsm-port-id
          - ^nsm-port-module-id
          - ^nsm-port-speed
      - paths => path:
        storage-shelf-path-info:
          - ^controller
          - ^^controller-uuid
          - ^initiator
          - ^initiator-side-switch-port
          - ^initiator-wwpn
          - io-kbps
          - iops
          - port-speed
          - ^target-port
          - ^target-side-switch-port
          - ^tpgn
      - power-supply-units => psu:
        storage-shelf-power-supply-unit-info:
#          - ^psu-crest-factor => crest_factor
#          - ^psu-fw-version => fw_version
          - ^^psu-id
          - ^psu-is-enabled => enabled
          - ^psu-location => location
          - ^psu-part-number => part_number
          - psu-power-drawn => power_drawn
          - psu-power-rating => power_rating
#          - ^psu-reset-capable => reset_capable
          - ^psu-serial-number => serial
          - ^psu-type => type
      - sas-ports => sas_port:
        storage-shelf-sas-port-info:
          - sas-negotiated-port-speed => negotiated_port_speed
          - ^^sas-port-id
          - ^sas-port-op-status
          - ^sas-port-power-status
          - sas-port-speed => port_speed
          - ^sas-port-type
          - ^sas-port-wwpn
      - shelf-bays => shelf_bay:
        storage-shelf-bay-info:
          - ^bay-has-disk
          - ^^bay-id
      - shelf-errors => shelf_error:
        storage-shelf-error-info:
          - ^component-location
          - ^corrective-action
          - ^error-text
          - ^^shelf-component
      - shelf-modules => shelf_module:
        storage-shelf-module-info:
          - ^es-serial-number
          - ^is-monitor-active
          - ^is-sas-master-module
          - ^module-fru-id
          - ^module-fw-revision
          - ^^module-id
          - ^module-is-reporting-element
          - ^module-latest-fw-revision
          - ^module-location
          - ^module-part-number
          - module-swap-count => swap_count
      - temperature-sensors => temperature:
        storage-shelf-temperature-sensor-info:
          - ^high-critical-threshold => high_critical
          - ^high-warning-threshold => high_warning
          - ^temp-is-ambient
          - ^temp-low-critical-threshold => low_critical
          - ^temp-low-warning-threshold => low_warning
          - ^^temp-sensor-id => sensor_id
          - temp-sensor-reading => reading
      - voltage-sensors => voltage:
        storage-shelf-voltage-sensor-info:
          - ^^voltage-sensor-id => sensor_id
          - ^voltage-sensor-location => location
          - voltage-sensor-reading => reading


export_options:
  instance_keys:
    - shelf
    - shelf_id
  instance_labels:
    - module_type
    - op_status
    - serial_number
    - model
    - state
    - vendor_name
    
