
name:                       StorageShelf
query:                      storage-shelf-info-get-iter
object:                     shelf


counters:
  storage-shelf-info:
    - disk-count
    - ^module-type
    - ^op-status
    - ^serial-number
    - ^shelf => shelf
    - ^shelf-id => shelf_id
    - ^shelf-model
    - ^^shelf-uid
    - ^state
    - ^vendor-name


plugins:
  Shelf:
    objects:
      - cooling-fans => fan:
        storage-shelf-cooling-fan-info:
          - ^^fan-id
          - ^fan-location => location
          - fan-rpm => rpm
      - current-sensors => sensor:
        storage-shelf-current-sensor-info:
          - ^^current-sensor-id    => sensor_id
          - ^current-sensor-location => location
          - current-sensor-reading => reading
      - power-supply-units => psu:
        storage-shelf-power-supply-unit-info:
#          - ^psu-crest-factor => crest_factor
#          - ^psu-fw-version => fw_version
          - ^^psu-id
          - ^psu-is-enabled => enabled
          - ^psu-location => location
          - ^psu-part-number => part_number
          - psu-power-drawn => power_drawn
          - psu-power-rating => power_rating
#          - ^psu-reset-capable => reset_capable
          - ^psu-serial-number => serial
          - ^psu-type => type
      - shelf-bays => shelf_bay:
        storage-shelf-bay-info:
          - ^bay-has-disk
          - ^^bay-id
      - shelf-errors => shelf_error:
        storage-shelf-error-info:
          - ^component-location
          - ^corrective-action
          - ^error-text
          - ^^shelf-component
      - shelf-modules => shelf_module:
        storage-shelf-module-info:
          - ^es-serial-number
          - ^is-monitor-active
          - ^is-sas-master-module
          - ^module-fru-id
          - ^module-fw-revision
          - ^^module-id
          - ^module-is-reporting-element
          - ^module-latest-fw-revision
          - ^module-location
          - ^module-part-number
          - module-swap-count => swap_count
      - temperature-sensors => temperature:
        storage-shelf-temperature-sensor-info:
          - ^high-critical-threshold => high_critical
          - ^high-warning-threshold => high_warning
          - ^temp-is-ambient
          - ^temp-low-critical-threshold => low_critical
          - ^temp-low-warning-threshold => low_warning
          - ^^temp-sensor-id => sensor_id
          - temp-sensor-reading => reading
      - voltage-sensors => voltage:
        storage-shelf-voltage-sensor-info:
          - ^^voltage-sensor-id => sensor_id
          - ^voltage-sensor-location => location
          - voltage-sensor-reading => reading


export_options:
  instance_keys:
    - shelf
    - shelf_id
  instance_labels:
    - module_type
    - op_status
    - serial_number
    - model
    - state
    - vendor_name
    
