name:                     Volume
query:                    volume-get-iter
object:                   volume

counters:
  volume-attributes:
    - volume-autosize-attributes:
      - maximum-size 
      - ^is_enabled                 => autosize_enabled
      - grow-threshold-percent

    - volume-id-attributes:
      - ^^instance-uuid             => instance_uuid
      - ^name                       => volume
      - ^node                       => node
      - ^owning-vserver-name        => svm
      - ^containing-aggregate-name  => aggr
      - ^style-extended             => style

    - volume-inode-attributes:
      - files-used
      - files-total
      
    - volume-sis-attributes:
      - compression-space-saved               => sis_compress_saved
      - deduplication-space-saved             => sis_dedup_saved
      - total-space-saved                     => sis_total_saved
      - percentage-compression-space-saved    => sis_compress_saved_percent
      - percentage-deduplication-space-saved  => sis_dedup_saved_percent
      - percentage-total-space-saved          => sis_total_saved_percent

    - volume-space-attributes:
      - expected-available
      - filesystem-size                       => filesystem_size
      - logical-available
      - logical-used
      - logical-used-by-afs
      - logical-used-by-snapshots
      - logical-used-percent
      - physical-used
      - physical-used-percent
      - size                                => size
      - size-available                      => size_available
      - size-total                          => size_total
      - size-used                           => size_used
      - percentage-size-used                => size_used_percent
      - size-used-by-snapshots              => snapshots_size_used
      - size-available-for-snapshots        => snapshots_size_available
      - snapshot-reserve-available          => snapshot_reserve_available
      - snapshot-reserve-size               => snapshot_reserve_size
      - percentage-snapshot-reserve         => snapshot_reserve_percent
      - percentage-snapshot-reserve-used    => snapshot_reserve_used_percent

    - volume-state-attributes:
      - ^state
      - ^status

plugins:
 - FlexGroup
 - Status:
    - status:
      label: state
      ok_value: online
              
export_options:
  instance_keys:
    - volume
    - node
    - svm
    - aggr
  instance_labels:
    - state
    - status
    - style
    - autosize_enabled
  graphite_leafs:
    - svm.{svm}.vol.{volume}
    - node.{node}.aggr.{aggr}.vol.{volume}

