
collector: Psutil
object: poller

schedule:
  - instance: 60s
  - data: 60s

counters:
  - status
  - CreateTime          => create_time 
  - CPUPercent          => cpu_percent
  - MemoryPercent       => memory_percent
  - NumThreads          => num_threads
  - NumFDs              => num_fds
  - NumChildren         => num_children
  - NumSockets          => num_sockets
  - MemoryInfo => memory:
    - RSS
    - VMS
    - HWM
    - Data
    - Stack
    - Locked
    - Swap
  - Times => cpu_times:
    - User
    - System
    - Iowait
  - IOCounters => io:
    - ReadCount       => read_count
    - WriteCount      => write_count
    - ReadBytes       => read_bytes
    - WriteBytes      => write_byes
  - NetIOCounters => net_io:
    - BytesSent
    - BytesRecv
    - PacketsSent
    - PacketsRecv
    - Errin
    - Errout
    - Dropin
    - Dropout
  - NumCtxSwitches => ctx_switches:
    - Voluntary
    - Involuntary


export_options:

  instance_keys:
    - poller
    - pid
    - status
  include_instance_names: False
