
name:                     CIFSvserver
query:                    cifs:vserver
object:                   svm_cifs

counters:
  - instance_name
  - cifs_op_count
  - cifs_ops
  - cifs_read_ops
  - cifs_write_ops
  - cifs_latency
  - cifs_read_latency
  - cifs_write_latency
  - connections
  - established_sessions
  - open_files
  - signed_sessions

export_options:
  instance_keys:
    - svm
  graphite_leafs:
    - svm.{svm}.cifs

override:
  - cifs_op_count: rate
