
name:                     Path
query:                    path
object:                   path

instance_key:             uuid

counters:
  - instance_name
  - instance_uuid
  - node_name             => node
  - read_iops
  - read_data
  - write_data
  - write_iops
  - total_data
  - total_iops
  - read_latency
  - write_latency

export_options:
  exclude_instance_name: True
  instance_keyslabels_to_emit: 
    - node
    - path
  #  - hostadapter # from plugin
  #  - target_wwpn # from plugin
  graphite_leafs:
    - node.{node_name}.hostadapter.{hostadapter}.target_wwpn.{target_wwpn}

