
name:                     Processor
query:                    processor
object:                   processor

instance_key:             uuid

counters:
  - node_name              => node
  - instance_name 
  - instance_uuid
  - domain_busy
  - processor_busy

plugins:
  - Processor

export_options:
  instance_keys:
    - node
    - processor
    - proc_count

