
name:                     Volume
query:                    volume
object:                   volume

instance_key:             uuid

counters:
  - instance_name
  - instance_uuid
  - vserver_name
  - node_name
  - parent_aggr
  - read_data
  - write_data
  - read_ops
  - write_ops
  - other_ops
  - total_ops
  - read_latency
  - write_latency
  - other_latency
  - avg_latency

export_options:
  instance_tag: volume_name
  include_instance_names: False
  include_keys:
    - instance_name
    - node_name
    - vserver_name
    - parent_aggr
  graphite_leafs:
    - svm.{vserver_name}.{node_name}.{parent_aggr}.{instance_name}
