
name:                     Volume
query:                    volume
object:                   volume

instance_key:             uuid

counters:
  - instance_uui
  - instance_name         => volume
  - vserver_name          => svm
  - node_name             => node
  - parent_aggr           => aggr
  - read_data
  - write_data
  - read_ops
  - write_ops
  - other_ops
  - total_ops
  - read_latency
  - write_latency
  - other_latency
  - avg_latency

export_options:
  instance_tag: volume_name
  include_instance_names: False
  include_keys:
    - volume
    - node
    - svm
    - aggr
  graphite_leafs:
    - svm.{svm}.{node}.{aggr}.{volume}
