
collector:          Zapi

# Order here matters!
schedule:
  - instance: 900s
  - data: 60s

objects:
  SystemNode:       node.yaml
  Aggregate:        aggregate.yaml
  Volume:           volume.yaml
#  LUN:              lun.yaml
  SnapMirror:       snapmirror.yaml
  StorageDisk:      disk.yaml
#  Qtree:            qtree.yaml
  Shelf:            shelf.yaml
