
collector:          Zapi

# Order here matters!
schedule:
  - instance: 600s
  - data: 180s

objects:
  SystemNode:       node.yaml
  Aggregate:        aggr.yaml
  Volume:           volume.yaml
  SnapMirror:       snapmirror.yaml
  StorageDisk:      disk.yaml
  Shelf:            shelf.yaml
