name:                     DiskConstituent
query:                    disk
object:                   disk_constituent
instance_key:             name

counters:
  - instance_name
  - cp_read_chain
  - cp_read_latency
  - cp_reads
  - disk_busy
  - disk_capacity
  - disk_speed
#  - display_name
  - io_pending
  - io_queued
  - node_name             => node
#  - physical_disk_name
#  - raid_group
  - raid_name
  - raid_type
  - total_transfers
  - user_read_chain
  - user_read_blocks
  - user_read_latency
  - user_reads
  - user_write_chain
  - user_write_blocks
  - user_write_latency
  - user_writes

plugins:
  - Disk

export_options:
  instance_keys:
    - aggr
    - node
    - disk
    - raid
    - plex
  instance_labels:
    - disk_speed
    - raid_type
