
name:                     HostAdapter
query:                    hostadapter
object:                   hostadapter

instance_key:             name

counters:
  - instance_name
  - node_name             => node
  - bytes_read
  - bytes_written

export_options:
  instance_keys: 
    - node
    - hostadapter
  graphite_leafs:
    - node.{node}.hostadapter.{hostadapter}
