
name:                     Processor
query:                    processor
object:                   processor

instance_key:             name

counters:
  - node_name             => node
  - instance_name 
  - domain_busy
  - processor_busy

plugins:
  - Processor

# only export node-level averages from plugin
# set this true or comment, to get data for each cpu
export_data: False

export_options:
  instance_keys:
    - node
    - processor
    - proc_count

